### ISSUE TITLE
video streams?

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#211]
Does this support webrtc video streams, or only audio?

edit: looks like only audio.

I'd like to get webrtc video streams.

How hard would it be to add this feature?

**Comment by craftecode** [comment]
This example on Hayden's Glitch might be relevant - https://glitch.com/~karaoke-nite

**Comment by kylebakerio** [comment]
Sadly, every user streams it themselves from a plain old URL, so it doesn't really help me. I already have every user streaming themselves to themselves from their own webcam and it displaying. The part I am unsure about it accessing the webRTC connection and passing video along it.

**Comment by kylebakerio** [comment]
So, I've gone ahead and (very roughly) hacked in the ability to do this. It's pretty much just a proof of concept, but I do have it up and running. Several things are not up to par, but I feel like with just a bit of cleaning up, it could be mergable. Just, this is very organized code, and I don't want to stop on toes and could use some guidance on what kind of tests I should be adding.

https://github.com/kylebakerio/networked-aframe

Still needs some glitches worked out. I was able to get two-way-video working, but usually only the second user gets to see the video of the first user, in my test right now. The current design of the code requires pre-adding a video element with id "webrtc-screen" in the 'assets' section in advance. That just suited me, though, and I'm not sure what the best way to go about this would be. I saw audio elements are dynamically added, but that's a bit different...

The other thing is I haven't really tested with more than two users right now (that's all my app is designed for), so I'll need to try that out as well.

Strange thing I noticed: my audio became suuuuuper laggy, like 15 seconds delayed, while the video stayed crisp and in sync. Probably just a webrtc issue, not sure what could be done in code to fix this, or whether that had anything to do with what I changed (I doubt it, as I mostly left the existing audio code in tact).

@haydenjameslee thoughts?

**Comment by kylebakerio** [comment]
Just adding for completeness, this is likely due to underlying problems in the webrtc adapter of NAF, as discussed [here](https://github.com/networked-aframe/networked-aframe/issues/217). The changes I made in my fork, while incomplete from an API point of view and hacky from a code quality point of view, should basically be what is needed at a fundamental level to add video.

Given that this project has no maintainer at the moment, I'd actually recommend switching back to easyrtc, which isn't made easy since it is officially deprecated in this repo. I've gone through and hacked a functional prototype of 0.7.1 using the old easyrtc adapter that is upgraded to open-easyrtc [here](https://glitch.com/edit/#!/naf-071-openeasyrtc?path=README.md%3A31%3A0). This demo probably works for most people, but in my particular case, it doesn't seem to--but that's likely due to the fact that I'm on a cellphone hotspot, which may require NAT-punchthrough (or something, not a webrtc expert) that isn't being implemented yet in the implementation.

Unfortunately, this means the video support will need to be re-implemented within the open-easyrtc adapter, _or_ the code in the webrtc adapter will need to be fixed.

**Comment by vincentfretin** [comment]
There is also this issue #18 

Note that janus and mediasoup adapters modified the getMediaStream signature from
`getMediaStream(clientId)`
to 
`getMediaStream(clientId, , type = "audio")`
so gettting the audio track by default for backward compatibility.
See janus adapter code here:
https://github.com/mozilla/naf-janus-adapter/blob/2ce5e2c4fbcda573f175f22062a50d8ead0680ad/src/index.js#L894
So if you are modifying the easyrtc adapter, you should do that as well.

**Comment by vincentfretin** [comment]
I have a project where I use the janus adapter and a component to display the video media on a plane geometry, inspired from an old version of the Hubs code. My component also does other things like display a slideshow of images, thumbnail of a youtube video that opens in a html modal, the component is a real mess, I can't share it lol.
Hubs recently refactored their code to create a `video-texture-target` component that can be used on an avatar now. This PR https://github.com/mozilla/hubs/pull/3925 highlights in fact all the needed code to display a video media.
I'm wondering if it would be interesting to extract this `video-texture-target` component and put it in a separate repo with the MPL licence, and add this new package as a dependency of networked-aframe.

**Comment by kylebakerio** [comment]
Yeah, I have a working fork now that has a 'networked-video-source' component that matches 'networked-audio-source', and otherwise has the same API. It provides a video stream that can then be used as the texture for a canvas. I use it for video streams from desktop connected clients.

If we used a more janus-adapter like api, though, which I think you're describing, then we could do things like stream from tabs with youtube, etc.

**Comment by vincentfretin** [comment]
There is not really a janus-adapter like api. :-)
You can have a `networked-video-source` with a `src` attribute pointing to a mp4 video url or a string "hubs://clients/${clientId}/video" that is the special case for screen sharing of webcam sharing of clientId.
If the `src` starts with "hubs://", you use 
```
const streamClientId = src.substring(7).split("/")[1]; 
const stream = NAF.connection.adapter.getMediaStream(streamClientId, "video")
```
This is how Hubs does it.

**Comment by kylebakerio** [comment]
Right. Using `const stream = NAF.connection.adapter.getMediaStream(streamClientId, "video")` is what I'm referring to as the janus-like API. That part happens behind the scenes in the adapter code for the other adapters.

**Comment by vincentfretin** [comment]
#57 proposed to implement `NAF.connection.adapter.setLocalMediaStream(stream)` as well like in the janus adapter to have more flexibility of what you share, audio track only of both audio and video tracks. Not sure how this is handled currently in open-easyrtc.

**Comment by kylebakerio** [comment]
indeed, it looks like it some point I gave that comment a thumbs up. I think it's an important feature to enable things like multiple people hanging out watching a shared video stream or something.

I also have found friction with the concept of adding multiple streams from one user (like, I want my mic audio stream as well as a youtube video's audio stream both going to someone else). I don't think NAF's paradigm enables this currently, it really seems to assume one stream per user. Perhaps Just adding more than one audio track would be an easy way to implement, haven't tried that / not sure if that is really allowed, but in theory sounds like it could be ok?

**Comment by vincentfretin** [comment]
Hubs is using an AudioSystem that can merge several audio tracks (microphone and audio from a Chrome tab for example) to a single audio track. `setLocalMediaStream` is given a stream with only one audio track and one video track for the RTCPeerConnection.
See https://github.com/mozilla/hubs/blob/master/src/systems/audio-system.js and there is the code there to enable Chrome AEC (Acoustic Echo Cancellation) too.

Enabling multiple audio tracks or multiple video tracks (like both camera and screen sharing) on the RTCPeerConnection is a different topic an a whole different beast. The janus adapter currently only allow 1 audio track and 1 video track on a peer connection. This may change when the multistream branch in janus-gateway is merged and if we modify the janus adapter to work with it, but this will require lots of changes.
Not sure about open-easyrtc.
I think mediasoup (used in new dialog adapter in Hubs) supports multistreams over the same RTCPeerConnection, but I don't think they currently use this feature to send several videos tracks.

**Comment by kylebakerio** [comment]
I have a hunch it would 'just work' with easyrtc adapter, but I'd have to test. Does the hubs code for merging audio tracks into on track work well, though? Should we merge that in?

**Comment by vincentfretin** [comment]
Note that the hubs AudioSystem is specific to janus and dialog adapters currently because it gets the mic audio track externally and use `setLocalMediaStream` on the adapter. Be careful about the different licences, Hubs code is MPL, networked-aframe is MIT, so it's not compatible to include Hubs code in the networked-aframe code base as far I understand.

To share the audio of a Chrome tab, you need to check the share audio checkbox when sharing the tab, you can easily miss it. I didn't manage to make it work though. I don't think sharing audio from Chrome tab works on Ubuntu, I read it only works on Windows, but I don't have Windows to test that. You can try on Hubs and let us know if it works. :)

For the question if open-easyrtc supports several video streams for a user, maybe @hthetiot can answer that.

**Comment by kylebakerio** [comment]
I've shared chrome tab audio from an ubuntu variant before, it has worked fine for me. I know the checkbox you're talking about, it is easy to miss and tripped me up the first time I was working with that feature. I haven't used hubs much, I'm not sure where to find their audio sharing feature though.

Good point about the different licenses. I'll look into that at some point, but looking into it quickly:

"The MPL is a simple copyleft license. The MPL's "file-level" copyleft is designed to encourage contributors to share modifications they make to your code, while still allowing them to combine your code with code under other licenses (open or proprietary) with minimal restrictions."

That's from mozilla's website. Sounds like it might work to allow us to backport code from their repo, but we should confirm a little more closely.

**Comment by kylebakerio** [comment]
Yeah, because the MPL is a file-level license, it explicitly allows borrowing code as long as the borrowed code itself continues to be under MPL, and is allowed to be incorporated into projects with other licenses. We may need to store mozilla-borrowed code in a separate folder and import it if we want to be careful on that front, but I need to check.

**Comment by vincentfretin** [comment]
Yes the borrowed code need to stay under MPL. To avoid troubles I suggested to create another package/repo with the code and use it as a dependency.

On Hubs, just click Share, Screen and select a tab with a youtube video. In my test sharing from Chrome Ubuntu and listening on Chrome Android, it doesn't appear to work. I don't hear the youtube audio. Anyway, it's not the Hubs repo here. :D

**Comment by kylebakerio** [comment]
As I mentioned, I have an app I built that uses this feature. We can try it later to see if it works on your system (audio sharing from another tab). If the hubs implementation doesn't work, it might have to do with their custom adapter code attempting to combine the mic and video stream failing.

**Comment by vincentfretin** [comment]
I edited my comment https://github.com/networked-aframe/networked-aframe/issues/211#issuecomment-784434198 about janus multistream and mediasoup to clarify the number of peer connections, please read it again. :)

**Comment by vincentfretin** [comment]
So the API `NAF.connection.adapter.getMediaStream(streamClientId, "video")` like it's currently done in the janus adapter is good when you have only one video track. What if you can have both screenshare and camera, and some other external video track?
Specifically with open-easyrtc, I think you can already share both screen and camera @hthetiot ?

You can read the hidden comments on the Hubs PR
https://github.com/mozilla/hubs/pull/3965 that will add simulcast. They started some discussions there.
The merging of audio tracks via the audio system I talked about in a previous comment will probably not be needed anymore for Hubs with mediasoup because they can now add several audio tracks to the publisher peer connection.

**Comment by kylebakerio** [comment]
That's right @vincentfretin, this system looks designed to share one stream. The question is, can a single stream have multiple video and/or audio tracks? If so, then it's theoretically able to be handled that way, though I'm pretty sure there are several places in the NAF source that all make the assumption that there's only one audio track (and my updates also made the assumption likewise that there would be only one video track). Not 100% sure, though, it may just be that it just assumes there is only one stream, now that I think about it, and then it's up to components like `networked-audio-source` (same for `networked-video-source` to take that stream and pull out whichever tracks they want and do what they will with it.

**Comment by kylebakerio** [comment]
Here's a discussion on the topic that seems relevant: https://groups.google.com/g/discuss-webrtc/c/vhKETlh4Jcw?pli=1

**Comment by kylebakerio** [comment]
My interpretation and experience--I think just having one stream and multi-track is the cleanest way to go. We can just pull out the tracks we want. I think it'd be the cleanest dev experience (one stream to one client, as opposed to unknown N streams per client), and also the least code update needed to existing NAF source.

**Comment by kylebakerio** [comment]
I'd propose that we try it and it doesn't work out in practice as nicely as we want, then we can consider updating to allow multi-stream per client.

**Comment by hthetiot** [comment]
I do not recommend to use multiple audio or video track for one steam, that not the way I have seen multiple stream be implemented anyway. The reason is you may end up with no control over what track is played by the MediaElement and that many SFU/MCU will not take the third track.

On Open-EasyRTC side you can register a new stream using the `easyrtc.register3rdPartyLocalMediaStream` API.

```
navigator.mediaDevices.getDisplayMedia({video: true}).then(function (stream) {
    easyrtc.register3rdPartyLocalMediaStream(stream, 'screen:1');

    // Then to add to existing connection
    easyrtc.addStreamToCall(easyrtcId, 'screen:1', function (caller, streamName) {

    });
})```

**Comment by hthetiot** [comment]
> Here's a discussion on the topic that seems relevant: https://groups.google.com/g/discuss-webrtc/c/vhKETlh4Jcw?pli=1

Forget about this it's from 2015 prior Transceiver and UnifiedPlan. There will be no mixing and no WebRTC library is doing it that way (Janus, Sip.js, Open-easyrtc, Twillio,...).

Related: https://paul.kinlan.me/crbug-894556-multiple-video-tracks-in-a-mediastream-are-not-reflected-on-the-videotracks-object-on-the-video-element/ original Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=894556&can=1&q=reporter%3Ame&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&desc=3

**Comment by hthetiot** [comment]
> I'm on a cellphone hotspot, which may require NAT-punchthrough (or something, not a webrtc expert) that isn't being implemented yet in the implementation

You need TURN server see https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_ice.md

**Comment by kylebakerio** [comment]
Thing is, you can just grab the track out of the stream and manipulate it directly. Just don't send the stream itself. You can make a new stream with the track you pulled.

I don't think there's a real problem here. I've written methods that grab audio tracks out of a media stream and then sent that track along directly to wherever I needed it.

**Comment by kylebakerio** [comment]
> You need TURN server see https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_ice.md

You don't need to respond to the original issue. I filed this when I was new to webrtc and to this library. I have learned a lot since then. This issue is no longer active and it's long solved.

**Comment by kylebakerio** [comment]
> A MediaStream can have multiple audio and video sources (e.g. because the user has multiple microphones, or because the real source of the stream is a media resource with many media tracks). The stream represented by a MediaStream thus has zero or more tracks.

> The tracks of a MediaStream are stored in two track lists represented by MediaStreamTrackList objects: one for audio tracks and one for video tracks.

https://dev.w3.org/2011/webrtc/editor/getusermedia-20120813.html

> A single MediaStreamTrack can represent multi-channel content, such as stereo or 5.1 audio or stereoscopic video, where the channels have a well defined relationship to each other. 

https://www.w3.org/TR/mediacapture-streams/#stream-api

**Comment by hthetiot** [comment]
Thank @kylebakerio that spec not implementation in the real world.

**Comment by hthetiot** [comment]
> You don't need to respond to the original issue. I filed this when I was new to webrtc and to this library. I have learned a lot since then. This issue is no longer active and it's long solved.

This is the same issue here, so it's not "closed", i understood that it was not the same topic, so I'm just trying to help no need to reply that way. I have been doing WebRTC since 2013, i have not realized you become a webrtc expert in 8 month. But if you read the public version of the chrome issue you don't have access you will see that there is a difference between spec and implementation, meaning you still have much to learn about WebRTC.

**Comment by hthetiot** [comment]
I will not try to help anymore, i don't like assholes.
Feel free to hide this comment @vincentfretin it's off topic.

**Comment by hthetiot** [comment]
> Specifically with open-easyrtc, I think you can already share both screen and camera @hthetiot ?

Don't bring me in issue with people that don't have basic respect for maintainer. If you need help next time poke me on slack or create an issue on Open-EasyRTC.

**Comment by kylebakerio** [comment]
hthetiot, I shared a more clearly worded version of the old spec, and then I shared the living modern spec which gives clear language explaining multi-track audio and multi-track video. I'm not sure why you're insulted or being aggressive. You seem to have misinterpreted me somehow? I'm sure you don't remember, but I actually contributed to your pull request for the open-easyrtc implementation in the past.

**Comment by kylebakerio** [comment]
I fully appreciated you likely know more than me on webrtc, but I've honestly never seen someone act that way on github. I'm kind of shocked, that's pretty crazy behavior for discussing some code spec and implementation details. I may very well be wrong, I am aware that the spec is one thing and implementation is another, but it seems like an extremely low-cost thing to attempt (could literally do this in a couple of hours), and it would be really convenient if it works. Nothing I've read or seen makes it clear to me that this won't work. If there's something in the chromium bug I can't see right now that says otherwise, by all means, please quote it.

I haven't disrespected you in any way, but ironically you're here discussing this issue on a repo where I happen to be the (new) co-maintainer, and have been shockingly disrespectful.

I'm not holding a grudge, and would value your input in the future, but next time I hope you can keep a more level head and. That was a really unreasonable explosion. It would have been enough to say that you're confident reality doesn't match the spec in your experience...

**Comment by hthetiot** [comment]
@kylebakerio fixing a typo in a readme is not a "pull request for the open-easyrtc implementation" LOL it's fixing documentation, not implementation. You clearly have a hight opinion of your contribution.

> https://github.com/open-easyrtc/open-easyrtc/pull/45

I replying like that because you clearly discard the help i provided after a was mentioned by @vincentfretin to assist here. That i did in the scope.

Please stop wasting my time, if you so smart you should have solved the problem by yourself longtime again.

**Comment by kylebakerio** [comment]
Alright, man. I updated the examples to be functional and advocated for your pull request. I didn't imply that I did some interesting code--the demos on your pull request just didn't work without the changes I made (not because you weren't capable of making it work, but simply because you hadn't made the time to do it properly), but whatever.

I don't really have a high opinion of my contribution at all--both of what we did there was extremely minor, it was just a version switch. On the contrary, you're the one acting like you're a god here.

I have solved any problems I've run into... As you said, long ago... And yes, as you say, it was pretty simple stuff.

"Discard the help" is a bit overbearing, and the over-leaning on emojis is embarrassing, man. You were just asked whether you had anything to say about supporting multiple video streams 'per user' in open-easyrtc. Both Vincent and I are certainly capable of implementing etiher multi-stream or multi-track (notwithstanding whether browser support for the spec is working or not), again, not sure why you're being so disparaging. Yes, Vincent asked something simple as a preliminary question; and?

**Comment by hthetiot** [comment]
> I happen to be the (new) co-maintainer, and have been shockingly disrespectful.

https://github.com/networked-aframe/networked-aframe/search?q=kylebakerio

I don't see any "contribution" here, only comments, make you first real contribution and implement multi stream then, so you can real call yourself "co-maintener", having right on a repository does not make you maintainer until you commit and I'm not talking using external tools to test package and adding it to the readme, I'm talking realm implementation of feature or fixing bugs here.

**Comment by kylebakerio** [comment]
We literally got right to the repo days ago, I'm in the middle of client work, I have separately had client work specifically implementing and adding networked aframe support to client projects (including fixing failed implementations by others), I have implemented video streaming on my own fork, have helped many people over the chat while this repo had no maintainer for months. I'm also the person who put together the working demo (and proof of problem with webrtc adapter) of going back to easyrtc (and later open easyrtc) with the last version of NAF while the webrtc adapter was broken that has been used by people in the meantime. 

Seriously dude. I don't know what your issue is, but fuck off and go get some counseling. Your problem isn't with me.

**Comment by hthetiot** [comment]
I recommend as a maintainer that you hide your off topic comments, like i did with mine, that a good practice.

Finally
> Seriously dude. I don't know what your issue is, but fuck off and go get some counseling. Your problem isn't with me.

You clearly use more bad language than I do, and attacking me personally and have a hight opinion of yourself, there is people that talk and people that do, i prefer the later.  No need to be vulgar. 

Generally people become maintainer after they contribute with PRs that get never and released, not when they make fix to their own fork and keep it for themselves and get right on repository that are abandoned by the original maintainer. I'm not attacking you personally like you do, i state fact based on what you did (or did not in that case) in term of actual contribution. You call you contribution "implementation" i call them external link to the readme, there is nothing wrong with stating a fact that you did not contribute to an implementation when you did not and i don't need to see a psy to say that just to make a github search.

**Comment by kylebakerio** [comment]
That's some quality trolling, buddy. Done here. 

I'm closing this issue and starting a new one, this one is a mess with more off-topic content at the beginning and end than is worth keeping.

**Comment by hthetiot** [comment]
Maintainer tips for you: You clearly don't know how github works, closing an issue will not prevent comments unless you disable them. Also closing an issue because of our of topic comment where you attacked a person personally will not solve anything and will prevent the original issue to get closed with original contexts. That why I suggested you to go on slack and hide you comment with "off topic", you clearly have much to learn. Only stupid people don't change their mind, this apply to me and you.

**Comment by hthetiot** [comment]
Ahah you delete comment because you are ashamed now, nothing get deleted on internet you should know that.

**Comment by vincentfretin** [comment]
@hthetiot I understand that it can be frustrating and may look as a waste of time to you to answer some of @kylebakerio comments who has less knowledge than you on the subject, especially the low level stuff with MediaStreamTrack and RTCRtpTransceiver. I don't have enough knowledge on it myself, this is why I ask questions here to have a better understanding of how we can support multiple videos for the easyrtc adapter in the hope you folks propose a good solution. I only know about basic RTCPeerConnection, MediaStream, MediaStreamTrack objects myself by reading the comments and history in the janus adapter code that supports only 1 audio and 1 video track per RTCPeerConnection and I understand that there are limitations in browser implementations in the past about it. I just started learning about transceiver not long ago by looking at the mediasoup documentation.
The usage of your emojis on Kyle comments like the thumbs down and laugh emoji wasn't a good reaction of your part @hthetiot. Be careful with emojis in communication, they can be interpreted very differently by different persons. I interpret those myself like some disdain feeling, so I understand how Kyle was feeling late in the discussion, although I disagree with his rude language and personal attack in the end, please avoid that here in the future Kyle.

About the title of co-maintainer... really everyone has different expectations about what a maintainer needs to be.
I gave the owner role on the networked-aframe organization to Kyle mainly to not be the only one having the permissions just in case, and because he was very active answering questions on the issues here and on Slack. He pushed me to be active again on slack and to be the new maintainer and I thank him for that. For me being a co-maintainer can just be answering some discussion issue and close them, or merge some small documentation changes if in the future I'm not available during a long period of time. I'm fine with that.

In the end it seems you did a rage PR to implements video in the easyrtc adapter, thanks for that, but I would prefer a more peaceful contribution next time. :)
