### ISSUE TITLE
Crazy-loud Audio feedback with webrtc

### ISSUE THREAD

**Issue by QuinnCiccoretti** [networked-aframe/networked-aframe#216]
First, please be careful when testing this.

If I have two tabs open of the webrtc example with audio, if I do not wear earbuds there is a stupid amount of audio feedback, like a ridiculously high volume. Please be **extremely careful** if you test this or replicate it with your own project because it definitely has the potential for ear damage.

In an ideal world perhaps no one would encounter this problem, but because of local testing and because accidents sometimes happen, I wanted to make an issue as a warning.

Edit: wanted to add an additional caution that this problem is exacerbated by untethered headsets like Vive Focus and Oculus Quest, since their speakers are located so close to your ears, and quite close to input microphone

**Comment by kylebakerio** [comment]
yeah, there is a spot in the code where it is suggested that we could inject a dev-friendly feedback-stopping feature, in the networked-audio-source component file. It's probably worth implementing, this is an obviously common experience.

**Comment by QuinnCiccoretti** [comment]
cool. i looked at the file and couldn't really figure out what you mean. If you could explain more, I could try and put up a PR

**Comment by kylebakerio** [comment]
https://github.com/networked-aframe/networked-aframe/blob/c75203a6d8bcc2d38803f4ca7d872ffbb4993ede/src/components/networked-audio-source.js#L30

Just remember seeing this line as I was hacking around.

I'm not sure if I understand it right. Seems to me that 'ownerId' will be set if it's a separate network entity, and that even if you are running two browser tabs side by side, you'll have different entities. But either the comment is wrong, or I don't understand it--maybe he refers to the ability to write some kind of tests or something.

So that aside, I'm not completely sure how to handle this. A quick google didn't turn up anything for pre-existing solutions to audio feedback, though I didn't look very hard. We could enable a dev-mode by default that requires confirming with a warning prompt before turning on mic that has to be disabled for production.

Maybe the best option is to use a localStorage setting. I haven't played with using localStorage for a single site opened in two tabs, but since localStorage is per-site, perhaps that's a good way for two open windows of the same site to use a common flag? We could set a 'using mic' flag, and onBeforeUnload turning that flag off. If the site loads and sees the flag is used, it can pop up a confirm dialogue explaining the risk to the user.

Did you have any thoughts?

**Comment by QuinnCiccoretti** [comment]
I like the idea of local storage, but it wont help if a user has a tab open in their browser and on the headset (as i did). That said, maybe thats not a super important use case.

I want to look into how NAF handles browser's built-in "Allow microphone" dialog, and whether we can hook in an additional warning

**Comment by kylebakerio** [comment]
The 'allow microphone' dialogue is just built into chrome. When you try to access the local media navigator object, either you can because the browser allows it, or you can't because it blocks it, or the browser handles it by querying the user. You can't really ride along on that. Also, that only shows up the first time you try to access in chrome--once you have given permission, it doesn't show up again. So that wouldn't help a developer who gives permission at one point, but only later tries it on two devices.

You'd just have to add in your own warning. It's not a hard thing to implement, but it might be unnecessarily tedious, so you'd probably put it behind a 'safe dev mode' flag. Which most devs would likely turn off so they don't have to answer it every time... which would then make it useless, unfortunately. :/

Two devices, headphones on one of them, is a harder problem to solve nicely.

Probably the dev mode flag should just turn off audio, and have a note by it, and there could be a separate flag for a warning when it is off.

So:

flag1: when 'true', turns audio off
flag2: when 'true', if flag1 is false, warns user every time before activating mic
flag3: production mode, when 'true', bypasses first 2 flags and allows audio

The point of flag 2 is to remind the dev to turn flag1 back on when they aren't actively testing the mic specifically.
