### ISSUE TITLE
Channel connection issues in 0.7.1

### ISSUE THREAD

**Issue by conwayanderson** [networked-aframe/networked-aframe#217]
In our implementation of 0.7.1, we noticed an issue where each user after the first one in a room wouldn't be able to talk and sometimes couldn't hear or move either. It appears there's an issue with the channel connections not being established.

At first we thought it was just our version. But then I reproduced this with 3 people in 3 different locations in the hosted demo here: https://haydenlee.io/networked-aframe/basic-audio.html

But when using 0.6 + easyRTC in this demo: https://glitch.com/~networked-aframe-audio, we didn't have this issue with the same users. Over and over it worked as expected. Unlike the 0.7.1 demo.

Ideally, we can figure out how to fix 0.7.1 so we don't have to rollback and switch our whole implementation. But I think there might be something wrong somewhere in the switch from easyRTC to the integrated WebRTC of 0.7.1. But it could be something else. Any ideas?

**Comment by naiteon** [comment]
I've noticed this behaviour as well. Is it safe to use 0.6 based on easyRTC? Sometimes the users won't move (i see checking the node logs that it seems a user keeps getting constantly disconnected/connected. That user wont move nor be able to hear or talk.

**Comment by conwayanderson** [comment]
What do you mean by safe? As in secure? When you experience the issues with
users not moving, is that in 0.7.1?

**Comment by naiteon** [comment]
Yep, it happens on 0.7.1. oh I meant to ask you if the 0.6 version is stable/reliable for production?

**Comment by conwayanderson** [comment]
We're not using it in production yet but it's working for demos. With the
current state of 0.7.1, I'm not sure if we have a choice without digging
further in & making some rewrites.

**Comment by kylebakerio** [comment]
Just chiming in here that I have also dealt with these issues in depth over the last couple weeks and talked a lot with conway about this, and while I haven't tested the 0.6 implementation myself, I did test both my own fork (where I was adding video streaming to the webrtc tracks), the non-forked download that I cloned down and deployed myself, and the demo deployed online (all of them 0.7.1 + webrtc adapter), and the 0.7.1 with webrtc only ever worked once for me when I wasn't testing locally. For some reason it usually at least partially works between my phone and computer, but as soon as I have someone else I test with, it has failed all but one time.

But if it isn't locally, 0.7.1 + webrtc adapter failed all but one time for me.

Adding a ton of logs in my forked version showed that the 'ontrack' wasn't firing on the local connections for user1, only for user2, but that would change when testing with real people who weren't local--in that case, the connection would start to get established, reach 'checking' iceconnectionstatus', pause, and then go to 'disconnected'.

I've gotten somewhat deep into the NAF code at this point, and while I'm considering 0.6, I don't want to regress and am interested in trying to sort out 0.7.1 and help improve the webrtc adapter, but so far there has been zero response and I hear rumors of this library having no maintainer after the last release and am not sure what the state of things is.

I've also considered just using the socketio adapter for NAF and opening my own webrtc channel connection entirely independent of NAF to get audio/video. But it isn't trivial and seems like it should make sense to fix the code for everyone else at this point rather than do a short term hack.

I looked at the janus adapter that hubs is using, but that's not peer to peer--all traffic is routed through the server, to in theory allow greater numbers of concurrent connections. That's not ideal for my use case, where I don't have all the server availability of mozilla, and don't want to add the complexity of running a dual server setup in languages and frameworks I don't want to become responsible for maintaining unnecessarily--that's a significant amount of extra overheard.

**Comment by naiteon** [comment]
I have spoken to Hayden Lee (the creator of the library) and mentioned this problem. On Jun the 6th he told me that I was running into a known bug to which they already have a fix in the master branch. They simply didn't release it yet but told me that hopefully they might ship it soon...

**Comment by naiteon** [comment]
A side note.... NAF uses tcp to keep track of the entities positions because it uses websocket. There is a project from this guy I met at Three.JS forums, which made a node module to keep track of objects position/rotation using UDP instead. The trick is using Webrtc DataChannel and make the browser consider the server as a webrtc peer. That solves latencies issues, You guys may wanna check it out. Perhaps we could adapt NAF to implement it?

https://geckosio.github.io

**Comment by kylebakerio** [comment]
Does NAF with the webrtc adapter not use the datachannels? It was my impression that it did.

**Comment by kylebakerio** [comment]
That is an interesting library, but given that we want audio, it might make more sense to try something like https://peerjs.com/ perhaps?

But yeah, I thought the socket connection was only being used as a connection broker when using webrtc... Are you sure that's not true? That would be surprising, since there is explicitly a webrtc non-audio example listed. In that case, what would the webrtc connection even be for?

**Comment by naiteon** [comment]
I think the webrtc adapter is meant for a peer to peer architecture not client-server... This library i shared uses webrtc udp in a client-server architecture by "tricking" the browser to believe the server is a peer.

"By default NAF uses WebSockets to send packets to other users. This follows a classic client-server architecture and uses the TCP network protocol. If you'd prefer to use a peer-to-peer architecture and would like to use the UDP network protocol you should use WebRTC."

**Comment by kylebakerio** [comment]
Sure, that's right. And that's what I want (p2p architecture).

It'd be interesting to make a new adapter that utilizes geckos to accomplish what you're talking about (webrtc for udp p2server), but that seems like a separate topic to me.

**Comment by kylebakerio** [comment]
Good to know they're working on the fix, I wish that was stated here. Now I don't have to waste my efforts duplicating their work. If it wasn't hearing that rumor from you now, I likely would have gone down that rabbit hole for nothing. Would be nice to get a timeline on that, though.

You say master branch, but we can see the master branch here, and it hasn't been touched in 21 days (since the release of 0.7.1 I think) so that's a little confusing. I guess they do their work secretly on some non-public branches? Would be nice to get some insight into what's going on.

**Comment by naiteon** [comment]
I know right. I am only sharing NAF's creator's private message to me on twitter here because I believe I'm not disclosing any private or sensitive data (Hayden don't be angry at me :) ) 

As for the NAF's webrtc adapter, yes, what I understand from it's documentation is that by using it instead of websockets, you are not having the server handling any objects' positions. Instead, you are switching to a totally p2p architecture. Which has its cons depending on the application. If you need smooth movements, you should not consider p2p due to the latency. But if it's something like a turn based game, that would be totally fine I think.

![Screen Shot 2020-06-29 at 20 38 53](https://user-images.githubusercontent.com/3129950/86066473-95b06b00-ba48-11ea-9207-5d02a83c95e6.png)

**Comment by kylebakerio** [comment]
oof, 23 days ago. 0.7.1 was released 21 days ago, 2 days after that message. No word since then?

**Comment by naiteon** [comment]
Unfortunately not :\

**Comment by kylebakerio** [comment]
Yeah, rumor is he left. He also lists 'networked aframe' as in his 'past' section on his twitter bio now.

I think the project is without a maintainer for the time being. Hopefully since mozilla uses it, it won't just die. Seems like a pretty important part of the aframe ecosystem.

Now sure what to do right now. I guess hack up a fork, and either that fork becomes the new version or eventually a maintainer comes and we can pull request it.

Unfortunate that the last release is so handicapped. From reading older issues, it was clear he wanted to make a 'pure' webrtc adapter that didn't rely on any underlying libraries, but it looks like he didn't get it quite right. At least it's a good guide going forward. Debugging it is a pain in the ass, though, since we don't have a working version to start with (and I'm relatively new to webrtc).

**Comment by kylebakerio** [comment]
Just thought I'd share here: my next thought for now is attempting to run the eastyRTC with 0.7.1 if possible, using this pul lrequest to open-easyrtc: https://github.com/networked-aframe/naf-easyrtc-adapter/issues/1

**Comment by kylebakerio** [comment]
Well, I went and did that for the last five hours. Here's the results:

https://glitch.com/edit/#!/naf-071-openeasyrtc?path=README.md%3A31%3A0

Basically, even with easyrtc, upgraded to openeasyrtc, plugged into either 0.6.1 or 0.7.1, I got the same issues: local feedback, but not working with other users. If you get different results, let me know, I only tested with one friend in germany, your mileage may vary--nothing has worked fo rus.

I cannot get any version or combinations of versions of things to work for me for audio with NAF at all. If anyone has any working example, please link it to me to test. I am starting to think this library has never actually reliably worked for audio. I only experienced working audio one time, when testing some version with conway, and I don't know which version that was.

**Comment by hthetiot** [comment]
The official PR for open-easyrtc support that I maintain was already opened here:
- https://github.com/networked-aframe/naf-easyrtc-adapter/pull/2

Thank to @kylebakerio that made a PR on master with more fixes, I did merge PR from @kylebakerio  into open-easyrtc branch instead, I'm willing to merge on master if that make it more easy for people to contribute.

**Comment by vincentfretin** [comment]
see #240

**Comment by kylebakerio** [comment]
I think it makes sense to close this issue once (if?) open-easyrtc is set here as the default adapter and is a working basic implementation. I don't think there's a high return on getting the 0.7 "webrtc" adapter working, and we can leave it aside for now, imo--if someone else wants to pick that up at some point, the work can still be there for them to find.

**Comment by vincentfretin** [comment]
I mark as wontfix for issues related to socketio/webrtc adapters.
