### ISSUE TITLE
Audio mute/unmute

### ISSUE THREAD

**Issue by lazarmitic** [networked-aframe/networked-aframe#266]
Is there a way to mute my mic when using `networked-audio-source` component. For example I want to add UI element that will allow user to mute his mic.

**Comment by vincentfretin** [comment]
Since #261 was merged, we have an API for the easyrtc adapter (the same api exists in the janus adapter), you can call:
```
NAF.connection.adapter.enableMicrophone(false)
```
We forgot to document it though, so I leave the issue open until we add it to the README.

In the easyrtc adapter only (not janus adapter), you have the same for the camera:
```
NAF.connection.adapter.enableCamera(false)
```

Add in the documentation:
- [ ] enableMicrophone(enabled)
- [ ] enableCamera(enabled)
- [ ] the video:true option to networked-scene

**Comment by lazarmitic** [comment]
Thanks!

**Comment by lazarmitic** [comment]
I just noticed that:

1. One client is connected and his mic is mutted.
2. Second client connects, he will be able to speak to first client.
3. First client unmutes his microphone and tries to speak, second client does not hear him.

I noticed that when second client connects, `getMediaStream` never resolves and `_setMediaStream` is never called.

Everything works fine if I don't mute the mic of first client.

I also notices some issues when more then two clients are connected. I will post detailed repro steps when I find out what's going on.

**Comment by lazarmitic** [comment]
It seems that if I unmute my mic, I have to call some function to nitify other clients so that they can resolve `getMediaStream`

**Comment by vincentfretin** [comment]
This should be fixed in master now.

**Comment by lazarmitic** [comment]
Thanks, when can I expect 0.8.1 version to be available :)

**Comment by vincentfretin** [comment]
The documentation was updated and 0.8.2 is released.

**Comment by lazarmitic** [comment]
Thanks! :D
