### ISSUE TITLE
Where is easyrtc.js?

### ISSUE THREAD

**Issue by ckasarda** [networked-aframe/networked-aframe#287]
In the example code, there is a reference being made to a file that no longer exists, called easyrtc.js. Does anyone know where this went or what replaces it? Thank you!

The line causes errors is this: `<script src="/easyrtc/easyrtc.js"></script>`

**Comment by lazarmitic** [comment]
Download that file from examples and host it on your server.

**Comment by ckasarda** [comment]
Awesome thanks it works now!

**Comment by vincentfretin** [comment]
It's weird you need to copy it, did you properly install dependencies with `npm install`?. See also my reply #286.

**Comment by vincentfretin** [comment]
I don't reproduce the issue with easyrtc not found.
If you follow the getting started instructions and copied the server and examples directories, ran `npm install` and `npm start`, the only instruction that may be missing to run an example is to edit `examples/shooter.html`
to replace
```
<script src="/dist/networked-aframe.js"></script>
```
by
```
<script src="https://unpkg.com/networked-aframe@^0.8.0/dist/networked-aframe.min.js"></script>
```
and http://localhost:8080/shooter-2.html is properly working.

**Comment by vincentfretin** [comment]
Cool, I added a note in https://github.com/networked-aframe/networked-aframe/commit/7a34d3ca964d6c0d3b533dd152a0fc16a0876585
We actually had this issue since I removed this little hack https://github.com/networked-aframe/networked-aframe/commit/11c4909ff925ea8dd906e1a00f8a339e1231c846 
I prefer to document it instead of having this hack used in the wild, which did a 404 Not Found on `/dist/networked-aframe.js` and then downloaded the latest version, version that could have been different from the one specified for the server part in `package.json`.
