### ISSUE TITLE
Cheap virtual production with NAF and Mediapipe

### ISSUE THREAD

**Issue by jimver04** [networked-aframe/networked-aframe#291]
Well my target is to make a multiplaying 3D environment where the persons are represented by cubes that have as textures their selfie without the background. It is a kind of cheap virtual production without chroma key background. The background is removed with MediaPipe Selfie-Segmentation wasm javascript code. The issue is that instead of having the other player texture on the cube (P1 should see P2, and P2 should see P1, each one sees his selfie. This means that P1 sees P1 and P2 sees P2 which is bad.

The full description of the issue can be found in 
https://stackoverflow.com/questions/68994847/using-self-segmentation-javascript-of-mediapipe-to-pass-user-selfie-as-a-texture

I have used : this.video.srcObject = canvasElement.captureStream(30); to capture the canvas video and add it as a texture to the cube. Is this correct ?

**Comment by vincentfretin** [comment]
I see you took the networked-video-source component that you modified.
In `networked-video-source` you have this line:
```
 this.video.srcObject = newStream;
```
You replaced it by:
```
this.video.srcObject = canvasElement.captureStream(30);
```

I don't see how your canvasElement draw the video track from newStream here.
It seems that selfie_segmentation take your webcam by default? You need to configure selfie_segmentation to use the video track from newStream. I'm not familiar with the lib, so I can't help you with it.

But be careful in my opinion you should not do the post processing on the receiving end, because here you're still sending your webcam with your background to all the other users, then you want to do the post processing when receiving each participant video? This won't be great for performance if you have more that 2 users. And this gives a false sense of security for the user. You still can show the webcam from another user with their background with a few lines of javascript in the console. :)

What you should normally is get the webcam, do the post-processing, then set the resulting canvas as a video track to the peer connection. I don't know how to do that with easyrtc, but I did a similar example with the janus adapter where I stream the scene canvas https://github.com/networked-aframe/naf-janus-adapter/blob/master/examples/audio-with-camera.html#L187-L189

**Comment by vincentfretin** [comment]
You may also be interested by the camera filters experiment that Hubs did here https://github.com/mozilla/hubs/pull/4352
that uses https://github.com/tensorflow/tfjs-models/tree/master/body-pix
Hubs is using their mediasoup adapter, but you can achieve the same with the janus adapter that also implements the `NAF.connection.adapter.setLocalMediaStream` API.

Good luck!

**Comment by jimver04** [comment]
Hi Vincent,

sorry for re-opening the issue but I think I have found the problem. Yes you are right, 

` this.video.srcObject = newStream; `

so this line is not suitable for changing the stream.
I searched the problem deeper for finding a way to change the stream.  

In EasyRtcAdapter.js  you have the following code:


```
  setMediaStream(clientId, stream) {
    // Safari doesn't like it when you use single a mixed media stream where one of the tracks is inactive, so we
    // split the tracks into two streams.
    const audioStream = new MediaStream();
    try {
      stream.getAudioTracks().forEach(track => audioStream.addTrack(track));
    } catch(e) {
      NAF.log.warn(`${clientId} setMediaStream Audio Error`, e);
    }

    const videoStream = new MediaStream();
    try {
      stream.getVideoTracks().forEach(track => videoStream.addTrack(track));
    } catch (e) {
      NAF.log.warn(`${clientId} setMediaStream Video Error`, e);
    }

    this.mediaStreams[clientId] = { audio: audioStream, video: videoStream };

    // Resolve the promise for the user's media stream if it exists.
    if (this.pendingMediaRequests.has(clientId)) {
      this.pendingMediaRequests.get(clientId).audio.resolve(audioStream);
      this.pendingMediaRequests.get(clientId).video.resolve(videoStream);
    }
  }
```

So there is no possibility to add video effects through a new MediaStream because you only accept camera video tracks this line:

`stream.getVideoTracks().forEach(track => videoStream.addTrack(track));`

It gets only camera tracks but not any other stream generated by any other method, e.g. drawing on a canvas and then capturing it such as with: 
`mediaStream = canvas.captureStream(frameRate);`

I will try to make a modification and let you informed. Having just a plain video stream is not enough I think. The library should allow to apply special effects on the stream such as removing the background at least.

**Comment by vincentfretin** [comment]
Yes we know that the easyrtc doesn't currently support any video stream, see #269
You will need to understand how open-easyrtc works and make changes to the `EasyRtcAdapter.js` to support it similar to `setLocalMediaStream` like it's done with the janus and hubs's dialog/mediasoup adapters that modify the publisher RTCPeerConnection. This is different than `setMediaStream` here, `setMediaStream` doesn't touch the publisher RTCPeerConnection.

**Comment by hthetiot** [comment]
"Yes we know that the easyrtc doesn't currently support any video stream"

I guess you mean "many" instead of "any" and the easyrtc always supported multiple streams, the issue lies in the api usage that need to be implemented in Network-a-frame adapter, but it's quite simple using simply 2 easyrtc api you mentioned in #269

**Comment by vincentfretin** [comment]
I know open-easyrtc supports several "many" video streams. By "any" here I meant the easyrtc adapter api (not open-easyrtc) and the networked-video-source component don't currently support replacing the camera video stream by your own video stream. Am I correct saying that?

**Comment by vincentfretin** [comment]
Cool video @jimver04 
I wanted to try your link, but currently it doesn't work, there are errors in the console. Anyway, I see you created a custom shader and putting the pixel fully transparent if the green minus red is at some threshold.
Instead of 
```
if (tex1.g - tex1.r > 0.15 && tex1.g - tex1.r > 0.15)
  gl_FragColor = vec4(0,0,0,0);
else
  gl_FragColor = vec4(tex1.r,tex1.g,tex1.b,1.0);
```
you can use I think:
```
if (tex1.g - tex1.r > 0.15)
  discard;
else
  gl_FragColor = vec4(tex1.r,tex1.g,tex1.b,1.0);
```
I looked at three shaders very recently, and found out how the `material.alphaMap` property worked.
The relevant parts are in [alphamap_fragment.glsl.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/alphamap_fragment.glsl.js) and [alphatest_fragment.glsl.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/alphatest_fragment.glsl.js). It uses `discard` to just not draw the pixel at all, it may be a little bit more performant than setting the pixel to 0,0,0,0, or maybe not, I'm not an expert at all, I just wanted to share this because I looked at this some days ago.

Once #294 is merged, if you are willing to contribute a small example of using some mediapipe filter using the new media stream API, I'll gladly review it.

**Comment by jimver04** [comment]
Thanks, I will use discard ! 
The problem with MediaPipe is that it is in beta version, it is not warrantied 100% that it will start properly (they say that it works for Chrome, but for me it has worked better for Firefox). It is in WebAssembly, and I am not very familiarized on how to debug it. However, their new version is much more stable that the older one. Let's hope that the will publish more stable versions.

ok, I will way for new EasyRTCAdapter and then make my contribution. 

Best,
Dimitrios

**Comment by jimver04** [comment]
Yes, I have used discard like below but it crashed. It needed to have something more ?.  I didn't search it. Perhaps I should write it differently. 

```
if (tex1.g - tex1.r > 0.15)
  discard;
else
  gl_FragColor = vec4(tex1.r,tex1.g,tex1.b,1.0);
```

**Comment by vincentfretin** [comment]
Ok, thanks for testing. I don't know why it crashes though.
