### ISSUE TITLE
remix demo is broken

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#347]
https://glitch.com/edit/#!/remix/naf-examples

always returns an error, won't load, won't even let you see the code. :/

**Comment by kylebakerio** [comment]
huh. Seems like it was likely some temporary downtime. working now…

**Comment by kylebakerio** [comment]
https://naf-examples.glitch.me/tracked-controllers.html

**Comment by kylebakerio** [comment]
this old copy is accessible, though I'm not sure what/how much has changed since then: https://glitch.com/edit/#!/8-2021-naf?path=examples%2Ftracked-controllers.html%3A97%3A0

**Comment by kylebakerio** [comment]
this link does work: https://glitch.com/edit/#!/remix/naf-project

**Comment by kylebakerio** [comment]
I contacted support and got some details:

> Good news: the app is running! You are very close to hitting your maximum disk space, and the npm install took 10 minutes. I think the first issue is that the ">= 16" node engine wasn't working and so the container was defaulting to Node 10 (we're going to look into why that string doesn't work). The other issue is that when npm installs take a long time, it can make it look like the editor is hanging because 10 minutes is a long time! Your project appears to have 2 webpack builds which could add to this time as well.

> I think this project like this would work best while boosted (which gives it more memory and disk space). I'll check on the project tomorrow to make sure it's running and let you know if we discover anything else.

(they did not update me the next day)

We should probably simplify this glitch demo.

**Comment by vincentfretin** [comment]
I'm using glitch for hosting the examples, I don't think we should promote remixing naf-examples, this includes all the tests stack you don't need and is doing the naf build (twice?), that's why it takes a long time to start up. You should start from naf-project template if you're starting a new glitch, it's using a released version of naf.
FYI I wrote in https://github.com/networked-aframe/networked-aframe/blob/master/docs/release-instructions.md how I resync this glitch. Specifying 
```
"engines": {
    "node": ">=16"
  },
```
worked before when I tested it in #318 and I see it's working properly in https://glitch.com/edit/#!/naf-project
Oh, I see now in the downloaded glitch archive it's using 
```
"engines": {
    "node": "16"
  },
```
Did I make a mistake last time I edited the file? Probably.

For naf-examples, currently I have the message "This project has been suspended".
I'll look into it and send email to the support once I figured out a new build/start strategy for the examples.
I knew it took a long time to start up, but doing the build twice? Ah because `npm install` does `npm run prepare` I guess? Ok that's explain it.

**Comment by vincentfretin** [comment]
See #348 for the changes I made. I sent an email to glitch to unsuspend the app.

**Comment by vincentfretin** [comment]
Glitch unsuspended the app and run the commands.
I had to run again:
```
rm -rf node_modules/*
npm install
```
to fix some module not found errors.
This is working properly now.

**Comment by vincentfretin** [comment]
I freed some disk space by running:
```
rm -rf .pnpm-store/
git prune
git gc
refresh

$ du -hs .git examples
36M     .git
12M     examples
2M for all the other files
```
The dashboard is reporting now 50 MB/200 MB. FYI naf-project is using 2 MB/200 MB.
The node_modules is not counted in this space, node_modules is a symlink to a volume:
```
$ ls -l node_modules
lrwxrwxrwx 1 app app 33 Jul 12 14:59 node_modules -> /rbd/pnpm-volume/app/node_modules
```




https://help.glitch.com/kb/article/101-disk-space-warning/

**Comment by vincentfretin** [comment]
FYI there is 7MB mp3 file `examples/assets/Tours-Enthusiast.mp3` that is not used by any example. I created a `.npmignore` file in https://github.com/networked-aframe/networked-aframe/commit/3f663ee81f674eb3056051489427ed9c04a03027 to not include the file in the next release so it won't take space in your node_modules on your machine if you're creating a naf project by following the getting started tutorial. :+1:

**Comment by kylebakerio** [comment]
> Did I make a mistake last time I edited the file? Probably.

They mentioned that that tag `">=16"` wasn't working properly, they had to change it to `16` to get it to work.

**Comment by kylebakerio** [comment]
Just want to mention that the point isn't remixing it, but the demos are linked in the readme, and those links weren't working. A ten minute load also wouldn't work.

I currently have a paid glitch account, I'd be willing to host it on my account and leave it boosted so it's always available.

**Comment by vincentfretin** [comment]
Thanks for the offer. I don't think this is needed, with the change I made using a package.json similar to naf-project, it wakes up under 10s now.
