### ISSUE TITLE
arrayified string sent with NAF update() call

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#354]
Looking at the argument passed to `update()` within a sync'd component, I see
```
0: "g"
1: "e"
2: "s"
3: "t"
4: "u"
5: "r"
6: "e"
color: "white"
gesture: "Fist"
hand: "right"
handModelStyle: "highPoly"
lastGesture: "Fist"
visible: true
```

the 0 -> 6 properties are not supposed to be there, and seem likely to be the string `"gesture"` being arrayified, (perhaps it's there at all because `gesture` is the property that was updated here?).

just some annoying junk data that points to an internal issue. Maybe this was some incomplete or flawed optimization that tries to only pass properties that have updated?

**Comment by vincentfretin** [comment]
I never saw something like that. What's your component and networked schema?

**Comment by kylebakerio** [comment]
Weird. The problem seems to have silently disappeared in the latest versions of the component. I was getting warnings for getting passed in props that didn't match the schema, but now I just... don't?

The schema was just a match for that, except without the 0 -> 6 properties. All were strings, except for color (which is color, which under the hood is also a string). 

I know I've seen stuff like this before in the past, but it's been too long for me to put my finger on it. When I see it again, I'll bring it up here again I guess.

**Comment by vincentfretin** [comment]
During your tests, if another participant was connected to the same room with old code, you could still be receiving the wrong data so having the warning, probably one participant was having the default networked schema so sending six values that probably correspond to two vectors position and rotation but it's really weird you got letters, or it was a previous version of your networked schema that may explain the letters better.
Your issue seems similar to https://github.com/networked-aframe/networked-aframe/issues/267#issuecomment-818034951 where all participants doesn't have the same networked schema.
If you still reproduce it later, please tell me.

**Comment by kylebakerio** [comment]
yes, I'm sure that was it. at some point during my testing I had an old tab left connected with a different schema that caused a variety of weird subtle behavior issues that threw me off for a while.
