### ISSUE TITLE
networked-hand-controls.js should inherit or respect MODEL_BASE from AFrame

### ISSUE THREAD

**Issue by Utopiah** [networked-aframe/networked-aframe#381]
I'm trying to run NAF offline and it works well.

I tried running the hands example but unfortunately couldn't load the model, which was a stranger error.

Upon checking the component `networked-hand-controls` https://github.com/networked-aframe/networked-aframe/blob/master/src/components/networked-hand-controls.js#L588 I noticed `MODEL_BASE` is being redefined.

I also noticed `customHandModelURL` which should be sufficient for my use case yet somehow despite setting using `networked-hand-controls="customHandModelURL:model.glb;"` it I still see in the console network errors trying to reach the CDN.

PS: what's quite surprising also is that if I remove the HMD, put it back, I see hands models at original coordinates. So... somehow something gets loaded, at least in the HMD, but maybe not displayed. Very confused.

**Comment by vincentfretin** [comment]
I'm not super familiar with the code. @kylebakerio may know better.

**Comment by kylebakerio** [comment]
It's not being redefined, iirc, it's _only_ defined there. Why do you say redefined? Just split the URL up that way to make the code cleaner.

`customHandModelURL` is not a well tested feature, just a kind of 'well, technically, someone might want this instead, so let's allow it and see what happens'. You are likely to get errors if your custom hand model doesn't have baked in animations with the same names--I didn't spend the time modifying that to be more flexible because this was already a big contribution and that was an edge case that so far we had no demand for.

What I imagine is happening is you are adding a custom model that lacks the animations, they load in, but then you get errors thrown when buttons are pressed and animations for gestures are triggered.

short term patch: look at the code and make sure you add matching animations to your model, even if they do nothing. (unless you actually want matching gestures, in which case you'll need to add the animations themselves, not just named blank animations, ofc).

Note that this is documented in the code:
```
    // these are for specifying a custom hand model URL; only allowed at init, not via update
    // (must correspond to existing models and have matching animations to work properly)
    customHandModelURL: { type: "string", default: '' }, 
 ```
 
 Also notice that there's a `visible` internal property. For your weird 'visible when I take it off and put it on' issue, that's most likely just the errors preventing visible from switching on, but then an update being fired because of some event that does trigger it related to entering/exiting webxr? just a guess, but not worth chasing down as it's very likely an artifact of what are effectively broken models.
 
 a slightly better patch would be a PR that bypasses the gestures according to a flag available in the schema. this should not only allow adding simpler models without gestures, but also turning off the gesture tracking if someone wanted that for less noisy network traffic, for example.

**Comment by Utopiah** [comment]
I copied the AFrame models as glb and put them in the local directory so I'm rather confident the models themselves including all necessary animations (as it works with AFrame offline).

What I meant by "redefined" is relative to AFrame, not NAF, but maybe there are some use cases were decoupling models from AFrame is useful.

**Comment by Utopiah** [comment]
Well that's a mindf*ck... when I visit https://naf-examples.glitch.me/tracked-controllers.html I also see no hands.

Will check via the remote debugging console.

**Comment by kylebakerio** [comment]
Sorry, I'm not sure I follow.

Perhaps I'm forgetting, but I don't think MODEL_BASE exists in A-Frame; pretty sure it's just something I wrote there so that the URL wasn't copy/pasted 6 times. Can you tell me what you think it should inherit from?

As you can see in the original hand-controls, the url is just stored hardcoded and copy/pasted: https://github.com/aframevr/aframe/blob/2c4509aa1a9a3c447c08be9facfea0c7d6a9e156/src/components/hand-controls.js#L5

No inheriting necessary.

Also, that shouldn't be being used if you're specifying custom models yourself I think? 

Can you share what url you are passing for the custom hand model url?

Does the 'someone else' have controllers simulated or attached/active?

And you are saying that the canonical example on naf-examples.glitch.me doesn't work for you, right? What headset are you using?

I'll try on my quest tomorrow and check to see that something hasn't broken in a recent browser update, I guess. For me, I'm seeing that my chrome extension for emulating a webxr session appears to have been broken presumably with recent updates, so I can't test the controller functionality itself on my browser at the moment.

**Comment by vincentfretin** [comment]
I just tested the tracked controllers example on Quest, I see the hand and controller.

**Comment by Utopiah** [comment]
> I just tested the tracked controllers example on Quest, I see the hand and controller.

Very strange, just tried again with a Quest 1 (freshly reset from yesterday) and Quest 2, both with latest OS and same problem, no hands.

**Comment by Utopiah** [comment]
> MODEL_BASE

You are correct, I meant `MODEL_URLS` which I discovered via https://github.com/aframevr/aframe/commit/d56b57071c46599083fe438736132298a58de1af yet I'd argue they have similar if not the same role. Consequently up to you to see if decoupling is better.

**Comment by Utopiah** [comment]
Just tried on another Quest 2 on another physical network and have the same problem, no hands visible in the official example on Glitch.

**Comment by kylebakerio** [comment]
Neat, didn't know about that--but that link is lacking in context and doesn't quite give enough info. I don't see that var on the `AFRAME` global in the browser; is it a build var only? If so, we don't have access to it, as this component is built in NAF, not within AFRAME itself.

I also just tested in a quest 2, and I also found the controller and hand both visible for me.

My guess would be something about the CDN isn't working for you...? Can you try just accessing the url directly from your quest browser and seeing if that succeeds or fails--or, ideally, hooking up chrome dev tools to observe what the network request for the model (and its response) look like?

Another option is some other error occurring for some reason that is interrupting the initialization of the hands. Would need dev tools to confirm. Could try spinning up a version that has a console instead, though.

Very odd.

**Comment by kylebakerio** [comment]
btw, @vincentfretin I did notice the controller buttons weren't moving when I pressed them. are we using the latest master aframe build there that adds this in? We aren't, and that's why I don't see it, right?

**Comment by kylebakerio** [comment]
@Utopiah if both the custom model url and the default model url both fail for you, in theory some other error could be causing both. But I am not sure what error that could be that is occurring on the canonical naf-examples demo just for you but not for either of us.   

> Checked via the remote debugging console and spot no error (beside a missing favicon).

But it sounds like you've done this, and also thus confirmed that there are no errors...???

Sounds very strange. Glad you reported, but so far there's no clues to follow on our end and no way to reproduce, it sounds like.

**Comment by vincentfretin** [comment]
> btw, @vincentfretin I did notice the controller buttons weren't moving when I pressed them. are we using the latest master aframe build there that adds this in? We aren't, and that's why I don't see it, right?

Yes we're using aframe 1.3.0 in the examples, not a master build, that's why.

**Comment by kylebakerio** [comment]
Also seems to work in emulated desktop with chrome extension, btw: 
![image](https://user-images.githubusercontent.com/6391152/205688867-1fee3ac0-ff18-4030-aa35-f4a8a2c16188.png)

@Utopiah have you tried [using the webxr emulator](https://aframe.wiki/en/#!pages/dev.md#Emulating_different_VR_devices_in_your_browser)?

**Comment by Utopiah** [comment]
This is what I see : 

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1076655/205696329-66e736d4-4e37-4678-82f5-bea750b3a60d.png">

which does load the glb

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1076655/205696416-ce82620d-558d-4ae0-9309-451d952d0cae.png">

yet does not show them

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1076655/205696920-81f56f38-d064-4fd7-b6e2-8dfd509848e6.png">

**Comment by kylebakerio** [comment]
quite odd. I do see that it's in tablet mode, wondered if that was related, but didn't seem to matter:

![image](https://user-images.githubusercontent.com/6391152/205963745-bbb69235-fa48-4fb1-b61c-85717880487a.png)

![image](https://user-images.githubusercontent.com/6391152/205964664-37338161-b8e5-4c07-81e1-bc94fb1c7c8c.png)

I don't have these color warnings show up, though...? Maybe that's relevant? Only clue I see here.

**Comment by kylebakerio** [comment]
if you 'exit vr' and then re-enter vr on the desktop emulator, do the hands then appear for you? what logs do you get then?

**Comment by Utopiah** [comment]
Using the emulator 0.3.3 with Chromium version 108.0.5305.0 (Developer Build) (64-bit) I do see that yellow hand model also but I fail to see how that is relevant if I don't see it in the headset.

**Comment by kylebakerio** [comment]
For debugging purposes, I guess. reaching at straws, trying to figure out what is going on, hard to debug at a distance with supposedly no errors or warnings and unable to replicate locally.

It's not just yellow hand model but also controller model... Actually, that's also interesting: you see neither hand nor controller model, right? Both are failing for you in headset? In both our demo and in your own copy of the code?

**Comment by Utopiah** [comment]
It's literally the Glitch link, without any modification to either code nor headset, even after a hardware reset.

**Comment by kylebakerio** [comment]
I'm curious about those warnings that were shown on yours. Why are you getting swapchain request/ignore, and flatshading? What OS/browser are you on? That's the only clue I see right now.

Next step would be coding up custom demos to chase this down. One might be to just statically display the models in your scene and make sure they can display at all. If that works, then the next thing would be putting breakpoints throughout the init chain of the networked-hand-controls component and seeing what shows up. Maybe duplicating the original demo but only showing one or the other of the hand or controller, to see if removing one allows the other to show up?

**Comment by Utopiah** [comment]
Using the Oculus browser, latest version
