### ISSUE TITLE
didn't manage to get hand tracking working

### ISSUE THREAD

**Issue by Utopiah** [networked-aframe/networked-aframe#394]
disentangling from https://github.com/networked-aframe/networked-aframe/issues/381

Could someone please share a working example with both URL and video recording of a real session (no emulator)?

**Comment by kylebakerio** [comment]
[hand-tracking-quest2.webm](https://user-images.githubusercontent.com/6391152/221280067-b5006577-c0ee-4456-8eea-d8921cf633be.webm)

Sure, motion in this vid is done in quest 2, recording is from desktop. url: https://naf-examples.glitch.me/tracked-controllers.html

Did it just now. Would love to know what's going on with your setup, but vincent and I have never been able to replicate your issues unfortunately, would need new info.

**Comment by kylebakerio** [comment]
Ah! 

This component is *not* compatible with the actual hand tracking API. I do realize the naming is confusing, but that's because it's inhereting the naming from the a-frame component that predates the hand-tracking API. In other words, this is a networked version of A-Frame's [hand-controls](https://aframe.io/docs/1.4.0/components/hand-controls.html) component.

Specifically, the hand controls component generates "hands" with gestures that match certain button click configurations. This component networks those gestures, and further supports a 'controller' model as an option that shows the actual buttons and joystick clicks instead of the faux-hand and faux-gestures.

In both cases, though, yes, controllers are required.

I've wanted to make a component that networks the skeleton pieces from the hand-tracking API--I think that would be magical and great--but I never got around to it. 

But I'm glad that clear it up. In this video demo, one hand is rendered as a controller, and one is rendered as a hand, just to show both options of display--but both are indeed controllers.

**Comment by Utopiah** [comment]
How would one go to start with just hand position? I'm thinking a sphere again would be a good start. It's not as precise as a hand model with position, rotation, and all joints, but I believe it's enough for some fun behaviors, including waving, pointing to objects, etc.

**Comment by Utopiah** [comment]
Working example https://twitter.com/utopiah/status/1711375479335227530 if others are interested. One can't "just" use a template with the hand tracked entity as it does not have a post but rather traverse through it to get the wrist (and optionally other joints) then make an invisible entity then network that one. An indirect solution with some overhead but seems to work.
