### ISSUE TITLE
Otheer users cameras position?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#467]
Hello, Is it possible to display other users avatar camera view displaying there avatar in a little window of some kind?

Joseph

**Comment by vincentfretin** [comment]
Please use Discussions instead of Issues, or just ask on discord only. It's only me that reply here lol, and I'm also on discord.
I see you already asked the question on discord and got an answer
https://discord.com/channels/479784974917042186/479787777949433900/1260990082479951872
You can indeed synchronize the position and rotation of the partipants (you already had this normally) and create another camera with those position and rotation. You can probably use https://github.com/diarmidmackenzie/aframe-multi-camera

**Comment by Therealjosephchrzempiec** [comment]
I have tried to ask in the discord. But I don't think anyone can help me. And I didn't want to botheryou because you was away. I will ask again there.  Thank you Vince
