### ISSUE TITLE
Let application handle getting local MediaStream

### ISSUE THREAD

**Issue by netpro2k** [networked-aframe/networked-aframe#57]
Related to #18, while working on adding support for screen sharing and video I realized that there are going to be a ton of different options a developer may want to set (source, resolution, FPS, etc) which all just back out to the adapter making a `getUserMedia` call and then passing that `MediaStream` off to a `PeerConnection`

Rather than continuing to add options to `networked-scene` to handle all these different cases, we should just allow the developer to get a `MediaStream` however they like and then pass it to the adapter. This would also allow the developer to request additional permissions at a later time and have the adapter renegotiate the PeerConnection for them.

I am thinking something like `NAF.connection.adapter.setLocalMediaStream(stream)`. If we want to keep the case of enabling audio "easy", we could have NAF call `getUserMedia` and `setLocalMediaStream` on the developers behalf as part of connecting if `audio: true` is passed. This also means we can probably ditch `enableMicrophone(bool)` as the developer can handle managing the `MediaStream` on their own however they like.

**Comment by vincentfretin** [comment]
The janus adapter has the `async setLocalMediaStream(stream)` (stream with one audio track and one video track only)  and `enableMicrophone(enabled)` api.

The easyrtc adapter has now a `addLocalMediaStream(stream, streamName)`/`removeLocalMediaStream(streamName)` api since #294 to add additional audio or video tracks, this was mainly to allow a screen share in addition to the camera. It also has `enableMicrophone(enabled)` and `enableCamera(enabled)` and is using the `audio: enabled` and `video: true` on `networked-scene` to get the mic and camera on user behalf. Note that `enableMicrophone(enabled)` is still needed to be able to disable the audio track on the peer connection, even if `networked-scene="audio:true"`. I created a separate issue for the easyrtc adapter to allow to specify audio and video constraints #300
